export const avatarReviewSpecs=[
  {
    id:'linework-v1',
    sourceDir:'Web/src/avatar/packs/linework',
    matrixFrames:'all',
    nonAdultFaceBoards:false,
    ageProof:false,
    nativeSizeProof:false,
    boardBackground:'#9b969c',
    boardSubtitle:'头像工坊 / 实际 SVG 图层诊断图板 · 不是固定人物图库，也不是玩家界面截图',
    mouthTolerance:0.03,
    eyeCheck:'optional-iris',
    expressionMarker:null,
    faceMarker:null,
    extraForbiddenSvg:[],
    headwearContract:false,
    outfitContract:false,
  },
  {
    id:'chibi-cute-v1',
    sourceDir:'Web/src/avatar/packs/chibi',
    matrixFrames:'adult',
    nonAdultFaceBoards:true,
    ageProof:false,
    nativeSizeProof:false,
    boardBackground:'#fffaf6',
    boardSubtitle:'实际可编辑 SVG 组合诊断 · 大头比例 / 极简五官 / 粗轮廓 · 不是固定整图',
    mouthTolerance:0.05,
    eyeCheck:'optional-iris',
    expressionMarker:'[data-expression-style="chibi"]',
    faceMarker:null,
    extraForbiddenSvg:['soft-paint','sp-hair','sp-skin'],
    headwearContract:true,
    outfitContract:true,
  },
  {
    id:'simple-flat-v1',
    sourceDir:'Web/src/avatar/packs/simple-flat',
    matrixFrames:'adult',
    nonAdultFaceBoards:false,
    ageProof:true,
    nativeSizeProof:true,
    boardBackground:'#fffaf6',
    boardSubtitle:'实际可编辑 SVG 组合诊断 · 细深灰线 / 平面色块 / 正常简化比例 · 不是固定整图',
    mouthTolerance:0.7,
    eyeCheck:'face-bounds',
    expressionMarker:'[data-expression-style="simple-flat"]',
    faceMarker:'[data-simple-flat-face]',
    extraForbiddenSvg:['data-expression-style="chibi"','cb-','sp-hair','sp-skin'],
    headwearContract:false,
    outfitContract:false,
  },
];

export const styleRelationships=[
  {type:'min-head-outfit-ratio',pack:'chibi-cute-v1',min:1.45},
  {type:'relative-head-outfit-ratio-max',pack:'simple-flat-v1',other:'chibi-cute-v1',factor:0.9},
  {type:'relative-face-width-max',pack:'simple-flat-v1',other:'chibi-cute-v1',factor:0.94},
];
