import type {ThemeCatalogOption} from '../catalog';

// 8D2：童老独立画稿的语义、适用性与文字权威。主题不是职业限制。
export const ageThemeHairOptions=[
 {"id":"child-twin-short-braids","label":"垂肩双辫","note":"女童 · 低位双短辫","description":"两束短辫从耳后向外下方垂落，顶上不扎圆髻。短辫止于肩上，保持儿童发量与圆短头形，不借用成年长辫。","theme":"common","keywords":["8D2","儿童","日常","双辫","短辫","低束"],"frames":["female.child"],"silhouette":"耳后对称两束短辫，平顺圆顶","closestAssetId":"child-side-braid","distinction":"单侧长辫改成两侧短辫，发量集中在耳后而非头顶","readability":{"96":"双短辫折面与收束点","64":"两侧下垂的短发量","48":"低位双尾"},"compatibilityKey":"braid","headwear":"none"},
 {"id":"child-side-loop","label":"侧环小髻","note":"女童 · 偏侧弯环","description":"头顶一侧向外弯出紧凑环髻，额发顺向偏梳，颈边收短。只保留一个偏侧束点，与对称双髻或耳边小辫区分。","theme":"common","keywords":["8D2","儿童","日常","侧环","小髻","偏梳"],"frames":["female.child"],"silhouette":"左上弯环髻，侧梳额发，无颈侧长尾","closestAssetId":"child-double-bun","distinction":"两个侧圆髻改为一个偏顶弯环，不以布结配色区分","readability":{"96":"偏顶弯环和侧梳方向","64":"单侧顶髻","48":"偏侧顶环"},"compatibilityKey":"pony","headwear":"none"},
 {"id":"child-folded-knot","label":"折髻短束","note":"男童 · 横折短髻","description":"发束在头顶向一侧折成扁短髻，额前分为宽短发面。比竖起的童子束发更低平，不画成年束冠或高帽身。","theme":"common","keywords":["8D2","儿童","日常","折髻","短束","横折"],"frames":["male.child"],"silhouette":"顶上一侧扁折髻，宽短额发","closestAssetId":"child-topknot","distinction":"竖圆顶髻改为偏侧横折，额发也改成宽短分片","readability":{"96":"横折发面与短额发","64":"扁折的偏顶体积","48":"低扁偏髻"},"compatibilityKey":"crop","headwear":"none"},
 {"id":"child-ribbon-tail","label":"束带短尾","note":"男童 · 偏侧短发尾","description":"一束短发从耳后斜向外侧收紧，末端分成两片短角，额发向后拢。出行时发量集中，尾端不过肩，不做成人高马尾。","theme":"traveler","keywords":["8D2","儿童","行旅","束带","短尾","出行"],"frames":["male.child"],"silhouette":"单侧耳后短尾，后拢额发，无高髻","closestAssetId":"child-half-up","distinction":"半束后发改成可见的单侧短尾，取消隐在脑后的长束","readability":{"96":"短尾分片及束带落点","64":"单侧耳后外展","48":"单侧短尾"},"compatibilityKey":"long","headwear":"none"},
 {"id":"child-helper-wrap","label":"窄结童巾","note":"儿童 · 包顶短结巾","description":"浅折布巾完整包住儿童头顶，侧后只留短布结，额边露少量短发。男童女童使用各自巾缘与鬓角画稿，不缩放成年包头。","theme":"labor","keywords":["8D2","儿童","劳作","童巾","包头","帮忙","短结"],"frames":["female.child","male.child"],"silhouette":"低折巾顶，完整额缘，侧后短布结","closestAssetId":"child-short-fringe","distinction":"裸发圆顶改成完整布巾面与短结，帽巾归 Hair 内层","readability":{"96":"巾面折角、短结和鬓发","64":"低折帽面与侧结","48":"短结包头"},"compatibilityKey":"crop","headwear":"integrated"},
 {"id":"child-outing-hat","label":"出游小笠","note":"儿童 · 圆顶宽檐","description":"圆缓笠顶连接外展帽檐，帽缘连续盖住额发，两侧笠绳留在背层。儿童笠顶较圆、比例较低，不将成年尖笠直接缩小。","theme":"traveler","keywords":["8D2","儿童","行旅","小笠","斗笠","出游","宽檐"],"frames":["female.child","male.child"],"silhouette":"圆缓顶、宽而下垂的笠檐","closestAssetId":"child-topknot","distinction":"竖向发髻替换为横向整片帽檐，儿童头框独立覆盖","readability":{"96":"圆顶编纹和笠檐连接","64":"圆顶宽檐","48":"圆笠宽檐"},"compatibilityKey":"crop","headwear":"integrated"},
 {"id":"elder-folded-low-bun","label":"横盘低髻","note":"老年女性 · 横向低盘","description":"发量向后下方盘成横扁折髻，两端在耳后下方露出，额发柔和归拢。低髻呈连续扁面而非耳旁圆球，保留老年独立发际。","theme":"common","keywords":["8D2","老年","日常","低髻","横盘","后拢"],"frames":["female.elder"],"silhouette":"后颈横扁髻，两侧下方短折面","closestAssetId":"elder-soft-bun","distinction":"单侧蓬松圆髻改成后颈横盘，不把圆球贴在耳廓旁","readability":{"96":"后颈折髻与柔和发际","64":"双侧低位横盘体积","48":"低横髻"},"compatibilityKey":"bob","headwear":"none"},
 {"id":"elder-braided-crown","label":"绕辫平髻","note":"老年女性 · 贴顶盘辫","description":"较细盘辫绕过头顶后向两侧收拢，髻体低平，额发分开露出克制的内发际。盘辫是头部轮廓的一部分，不是独立头饰。","theme":"common","keywords":["8D2","老年","日常","盘辫","平髻","绕顶"],"frames":["female.elder"],"silhouette":"低平拱辫，短侧发，顶上没有高圆髻","closestAssetId":"elder-coiled-bun","distinction":"竖向圆盘髻改为贴顶横拱辫，不靠发色增加新款","readability":{"96":"低拱盘辫的分段","64":"低平绕顶发量","48":"横拱平髻"},"compatibilityKey":"braid","headwear":"none"},
 {"id":"elder-flat-topknot","label":"平束老髻","note":"老年男性 · 扁束小髻","description":"头顶以一束扁平发结收住短发，额前发面向后拢，颈旁不垂长尾。发结是横向折片，区别于老者短束的竖圆结。","theme":"common","keywords":["8D2","老年","日常","平束","扁髻","短发"],"frames":["male.elder"],"silhouette":"低扁横结，后拢额发，短颈边","closestAssetId":"elder-short-bound","distinction":"竖向小髻改为横扁折结，后拢发面不缩放成年短束","readability":{"96":"横结折面与后拢发际","64":"低扁顶结","48":"平顶小结"},"compatibilityKey":"crop","headwear":"none"},
 {"id":"elder-nape-tail","label":"垂肩短束","note":"老年男性 · 颈侧短束","description":"后发在一侧颈旁收成细短发束，末端贴着肩上自然垂下。上额保留老年后拢发际，区别于两侧蓬散的松拢长发。","theme":"traveler","keywords":["8D2","老年","行旅","颈侧","短束","垂肩"],"frames":["male.elder"],"silhouette":"单侧颈旁细短尾，无高髻","closestAssetId":"elder-loose-back","distinction":"两侧松散长发收成一侧短束，尾端不伸到胸前","readability":{"96":"颈侧发束和末端折面","64":"单侧贴肩短尾","48":"细短侧尾"},"compatibilityKey":"long","headwear":"none"},
 {"id":"elder-soft-work-wrap","label":"软折布巾","note":"老年 · 低折包巾","description":"布巾沿老年头围低低包覆，斜折巾面在侧后收成扁结，短鬓发仍可见。男女分别绘制巾缘和后结，不复制成年大包头。","theme":"labor","keywords":["8D2","老年","劳作","布巾","包头","软折","短结"],"frames":["female.elder","male.elder"],"silhouette":"低软折巾面，扁短后结，灰白鬓发","closestAssetId":"elder-swept","distinction":"裸发后拢改成连续软巾帽身，仍保留短鬓发","readability":{"96":"斜折巾面、扁结与鬓发","64":"低软帽身","48":"软折包巾"},"compatibilityKey":"crop","headwear":"integrated"},
 {"id":"elder-low-brim-cap","label":"矮檐便帽","note":"老年 · 低顶软檐帽","description":"低圆帽顶与微微外翻的短软檐连接，额缘完整、两侧没有帽翅。配老年短鬓发，整洁便装不使用官帽徽饰或顶珠。","theme":"merchant","keywords":["8D2","老年","商铺","便帽","矮檐","圆顶","整洁"],"frames":["female.elder","male.elder"],"silhouette":"低圆帽顶、外翻短檐、灰白鬓发","closestAssetId":"elder-swept","distinction":"贴头发面改成低顶短檐帽，不用官帽翅或顶珠区分","readability":{"96":"圆顶与外翻短檐的连接","64":"低顶两侧短檐","48":"扁圆檐帽"},"compatibilityKey":"crop","headwear":"integrated"},
] as const satisfies readonly ThemeCatalogOption[];

export const ageThemeOutfitOptions=[
 {"id":"child-arc-collar","label":"弧领小衫","note":"女童 · 短弧翻领","description":"两片圆短领面从颈侧向外翻开，内衫只露在中央，外衣前片连续到底。圆短翻领配窄儿童肩形，不堆叠成人大领片。","theme":"common","keywords":["8D2","儿童","日常","弧领","圆领","小衫"],"frames":["female.child"],"silhouette":"两片短圆翻领，窄肩连贯前片","closestAssetId":"child-play-jacket","distinction":"细直外缘改为圆短翻领，领端压住内衫而非漂浮","readability":{"96":"短圆翻领与内衫遮挡","64":"双弧领面","48":"圆短双领"},"compatibilityKey":"tee"},
 {"id":"child-petal-overcoat","label":"短肩叠褂","note":"女童 · 斜开短肩褂","description":"短肩外褂采用偏斜开口，一侧前片横斜包住内衫，肩边留完整弧面。开口关系不对称，不把两片外褂缩成围裙吊带。","theme":"common","keywords":["8D2","儿童","日常","短肩","叠褂","斜开口"],"frames":["female.child"],"silhouette":"弧形短肩，偏斜外搭开口","closestAssetId":"child-fine-robe","distinction":"对称方领改为偏斜整片外搭，不加胸口裙腰","readability":{"96":"偏斜开口与短肩层次","64":"斜开口的完整外片","48":"偏斜叠褂"},"compatibilityKey":"knit"},
 {"id":"child-side-fastened","label":"侧襟童衫","note":"男童 · 侧合整襟","description":"小团领沿一侧接入完整斜合前襟，肩部收短，中央没有竖向开缝。侧扣仅辅助结构，辨识依靠宽斜襟面。","theme":"common","keywords":["8D2","儿童","日常","侧襟","童衫","团领"],"frames":["male.child"],"silhouette":"小团口、偏侧大襟、紧凑肩身","closestAssetId":"child-apprentice","distinction":"细侧缝改为宽斜合襟面，正面主体保持整片","readability":{"96":"团口接斜襟的闭合位置","64":"偏侧斜合衣片","48":"侧斜襟"},"compatibilityKey":"shirt"},
 {"id":"child-straight-jacket","label":"直缘小袍","note":"男童 · 团口直襟","description":"窄圆领口接正中直襟，两边门襟间留一小片完整内衫。衣面竖向舒展但肩部短窄，不在胸像底端添加腰带表示袍长。","theme":"common","keywords":["8D2","儿童","日常","直襟","小袍","常服"],"frames":["male.child"],"silhouette":"小圆口接平行直缘，短窄肩","closestAssetId":"child-short-robe","distinction":"斜交领改为正中直开口，不靠衣长或颜色定义新款","readability":{"96":"圆口与平行门襟","64":"小圆口直襟","48":"细直襟"},"compatibilityKey":"tee"},
 {"id":"child-helper-smock","label":"帮忙罩衣","note":"儿童 · 敞口短罩","description":"敞口罩衣从肩头连成完整左右前片，中央露团领内衫，外衣肩部短而收拢。用于轻便日常帮忙，不表示儿童具有固定职业。","theme":"labor","keywords":["8D2","儿童","劳作","罩衣","帮忙","无袖","敞口"],"frames":["female.child","male.child"],"silhouette":"短肩敞口罩衣，完整左右前片","closestAssetId":"child-helper","distinction":"单交领短褐改为敞口罩衣，两侧有真实衣片面积","readability":{"96":"短肩外片与团领内衫","64":"敞口两层衣装","48":"短肩敞褂"},"compatibilityKey":"jacket"},
 {"id":"child-outing-cape","label":"圆摆小披","note":"儿童 · 圆弧短披","description":"圆弧短披从颈口盖向两肩，披边止于上胸，下面仍是完整内衣。边缘以弧线形成短披轮廓，不是底部横挡板或围脖细条。","theme":"traveler","keywords":["8D2","儿童","行旅","小披","圆摆","出游","披肩"],"frames":["female.child","male.child"],"silhouette":"圆弧肩披，短侧摆，交领内衫","closestAssetId":"child-winter","distinction":"竖向夹袄改为横向圆弧肩披，主衣片继续向下","readability":{"96":"圆弧披边与内衫连接","64":"圆肩短披","48":"圆摆肩披"},"compatibilityKey":"knit"},
 {"id":"elder-shawl-wrap","label":"搭肩暖衫","note":"老年女性 · 斜搭软披","description":"宽软披面从一侧肩头斜搭到另一侧，布边沿肩胸缓缓转折，内衫交领只露中央。老年落肩画稿独立绘制，不将成年披帛整体缩放。","theme":"traveler","keywords":["8D2","老年","行旅","暖衫","搭肩","软披","出行"],"frames":["female.elder"],"silhouette":"低落肩、斜搭宽软披面","closestAssetId":"elder-warm-coat","distinction":"纵向敞口罩衣改为横斜肩披，外布连续而非细带","readability":{"96":"宽披面折向及内衫开口","64":"横斜暖披","48":"斜搭肩披"},"compatibilityKey":"knit"},
 {"id":"elder-rounded-lapel","label":"圆折长褂","note":"老年女性 · 圆顺宽领","description":"宽领由颈侧圆顺外翻，再沿两片前襟延伸出画布；内衫收在领口里。整洁感来自连续圆领面，不用金边徽饰表示身份。","theme":"merchant","keywords":["8D2","老年","商铺","圆折","宽领","对襟","长褂"],"frames":["female.elder"],"silhouette":"两侧圆顺翻领接宽门襟，舒缓落肩","closestAssetId":"elder-fine-robe","distinction":"窄直门襟改为从颈旁翻出的圆宽领，保持两片前身","readability":{"96":"圆翻领的折面与落点","64":"圆宽领接对襟","48":"圆宽双领"},"compatibilityKey":"knit"},
 {"id":"elder-deep-front","label":"深缘常袍","note":"老年男性 · 深交宽缘","description":"深交领以较宽的完整领面包住前胸，前片斜向落到另一侧下缘。肩部宽松下垂，不用成年紧肩短袍替代。","theme":"common","keywords":["8D2","老年","日常","深缘","宽交领","常袍"],"frames":["male.elder"],"silhouette":"宽松落肩，深交宽领，完整大襟","closestAssetId":"elder-long-robe","distinction":"浅细交领改为深交宽领，宽面连续接入主衣片","readability":{"96":"深交宽缘和大襟走势","64":"深斜宽领","48":"宽深交襟"},"compatibilityKey":"shirt"},
 {"id":"elder-short-overcoat","label":"落肩短罩","note":"老年男性 · 合口落肩","description":"短罩衣从颈侧低低落向肩头，外衣在前胸偏侧合拢，内衫圆领清楚露出。主衣片有完整面积，不画窄吊带或硬直肩甲。","theme":"common","keywords":["8D2","老年","日常","落肩","短罩","合口"],"frames":["male.elder"],"silhouette":"宽松落肩，偏侧合拢外片","closestAssetId":"elder-simple-robe","distinction":"单层团领改为低落肩叠穿外罩，闭合移向一侧","readability":{"96":"低落肩外片与团领内衫","64":"宽肩偏侧合口","48":"落肩短罩"},"compatibilityKey":"tee"},
 {"id":"elder-work-overrobe","label":"宽肩劳褂","note":"老年 · 宽松敞口褂","description":"宽松外褂由低肩连向左右两片前身，中间留宽开口，露出朴素内衫。肩身采用老年独立轮廓，劳作感不依赖补丁与深褐配色。","theme":"labor","keywords":["8D2","老年","劳作","宽肩","劳褂","敞口","外搭"],"frames":["female.elder","male.elder"],"silhouette":"低宽肩与两片敞口外褂，团领内衫","closestAssetId":"elder-work-jacket","distinction":"带补缀的单交领衣改为宽松敞口外褂，取消补丁主识别","readability":{"96":"完整外片与宽开口","64":"宽肩敞褂","48":"低肩双前片"},"compatibilityKey":"jacket"},
 {"id":"elder-travel-mantle","label":"合领行罩","note":"老年 · 包颈肩罩","description":"厚实肩罩从颈口合拢向两肩圆缓展开，前胸有清楚的交叠尖圆端，内衫继续向下。包裹感来自宽领和肩罩体积，不用现代拉链或金属扣。","theme":"traveler","keywords":["8D2","老年","行旅","行罩","合领","肩罩","包裹"],"frames":["female.elder","male.elder"],"silhouette":"包颈宽领，圆缓肩罩，交叠前端","closestAssetId":"elder-padded-robe","distinction":"对襟夹棉改为合领肩罩，宽外披与内衫分层","readability":{"96":"领面交叠与圆缓披边","64":"包颈宽肩罩","48":"合领宽披"},"compatibilityKey":"knit"},
] as const satisfies readonly ThemeCatalogOption[];
