import type {ThemeCatalogOption} from '../catalog';

// 主题只是作者与检索信息；不限制职业，不写入 Recipe。
export const themeHairOptions=[
 {"id":"adult-loop-bun","label":"弯月盘髻","note":"横向弯月髻 · 偏侧收发","description":"横向盘髻从左上头顶弯起，额发向侧面收拢。区别于耳后低髻，缩小时主要看头顶偏侧的弧形体积。","frames":["female.adult"],"compatibilityKey":"bob","headwear":"none","keywords":["常服","8D1","8D1-A","盘发","偏侧","弯月","普通","日常"],"theme":"common","silhouette":"头顶左侧横弯髻，偏侧额发，颈旁无垂尾","closestAssetId":"low-bun","distinction":"髻体从耳后下方移到头顶偏侧，以横弧而非耳后圆结形成差异","readability":{"96":"髻体弧线和侧梳额发","64":"左上偏侧体积","48":"偏侧顶髻"}},
 {"id":"adult-ribbon-fall","label":"素带半披","note":"两侧披发 · 低位布带","description":"左右后发垂至肩边，末端外展，低位素带收住一侧。比长发低束更松散，辨识依靠肩旁的两片发量而非布带颜色。","frames":["female.adult"],"compatibilityKey":"long","headwear":"none","keywords":["常服","8D1","8D1-A","半披","长发","布带","普通","日常"],"theme":"common","silhouette":"两侧披发齐肩外展，低位布带收住一侧","closestAssetId":"adult-long-tied","distinction":"保留左右两片松散披发，不把后发收成一根低尾","readability":{"96":"左右发片与低束带","64":"肩旁双侧发量","48":"外展披发"}},
 {"id":"adult-flat-knot","label":"扁束发髻","note":"横扁发结 · 中间束带","description":"头顶横向折叠成扁宽发结，以窄带在中间收紧。与高髻的竖向体积区分，男女共用成年头部画稿。","frames":["female.adult","male.adult"],"compatibilityKey":"crop","headwear":"none","keywords":["常服","8D1","8D1-A","扁髻","束发","横向","普通","日常"],"theme":"common","silhouette":"头顶低扁横结，中分额发，窄束带","closestAssetId":"bound","distinction":"把竖向小束髻改为横扁发结，不靠束带颜色区分","readability":{"96":"横结两端和中分额发","64":"低扁横向髻体","48":"横扁顶结"}},
 {"id":"adult-center-part","label":"中分短束","note":"中分额发 · 颈后短束","description":"中分额发在两侧折向耳后，后发只在颈旁露出短角。没有突出的顶髻，轮廓比半束长发短而收敛。","frames":["male.adult"],"compatibilityKey":"bob","headwear":"none","keywords":["常服","8D1","8D1-A","中分","短束","后发","普通","日常"],"theme":"common","silhouette":"没有突出顶髻，中分额发，颈旁短角","closestAssetId":"adult-half-up","distinction":"去掉高束点与长垂发，只留下收短的后发轮廓","readability":{"96":"中分折向耳后，颈旁短角","64":"无顶髻的短后发","48":"紧凑圆顶"}},
 {"id":"adult-work-braid-coil","label":"编辫盘髻","note":"绕顶编辫 · 收拢后发","description":"粗编辫绕过头顶形成一圈起伏的外轮廓，后发完全收拢。劳作感来自集中发量，不靠灰色或细碎发丝区分。","frames":["female.adult"],"compatibilityKey":"braid","headwear":"none","keywords":["劳作","8D1","8D1-A","编辫","绕顶","盘髻"],"theme":"labor","silhouette":"粗辫绕顶形成起伏边缘，侧后不垂辫","closestAssetId":"adult-side-braid","distinction":"把侧垂长辫收拢到头顶，改变发量分布","readability":{"96":"绕顶编辫分段","64":"起伏的绕顶发量","48":"宽拱辫冠"}},
 {"id":"adult-work-fold-wrap","label":"折角包头","note":"折角布面 · 短后结","description":"两块折角布面围住头顶，侧后留短结。帽身用完整前层表现，与圆顶包头的区别是明显的折面和收短的布尾。","frames":["female.adult"],"compatibilityKey":"crop","headwear":"integrated","keywords":["劳作","8D1","8D1-A","折角","包头","头巾"],"theme":"labor","silhouette":"斜折帽顶，左右折角，短后结","closestAssetId":"work-headscarf","distinction":"以折面外包络替代圆顺布巾，布尾收短","readability":{"96":"完整帽身和两侧折面","64":"不对称折角帽顶","48":"折角包头"}},
 {"id":"adult-work-front-knot","label":"额结汗巾","note":"窄汗巾 · 额侧布结","description":"窄汗巾环绕额上，左额侧有明确布结和一截短尾，顶部发髻仍露出。不同于全包头巾，主体依然是束发。","frames":["female.adult","male.adult"],"compatibilityKey":"crop","headwear":"integrated","keywords":["劳作","8D1","8D1-A","汗巾","额结","窄带"],"theme":"labor","silhouette":"窄额带加额侧结，露出完整发髻","closestAssetId":"work-headscarf","distinction":"由全包布巾变为露顶汗巾，布面不覆盖大部分头部","readability":{"96":"额侧布结和窄带","64":"露出顶髻的汗巾","48":"发髻与额侧结"}},
 {"id":"adult-work-short-tail","label":"短尾束巾","note":"额前窄巾 · 侧后短尾","description":"额前薄巾约束碎发，短发尾从侧后垂至颈旁并再次束住。短尾比束辫更粗整，不添加垂到胸前的长辫。","frames":["male.adult"],"compatibilityKey":"pony","headwear":"integrated","keywords":["劳作","8D1","8D1-A","短尾","束巾","额带"],"theme":"labor","silhouette":"偏梳短发、额前窄带、耳后粗短尾","closestAssetId":"adult-braided-tail","distinction":"取消长编辫分段，集中为颈侧粗短束尾","readability":{"96":"短尾折面与额带","64":"侧后短尾","48":"不对称短尾"}},
 {"id":"adult-shop-fan-bun","label":"扇形整髻","note":"扇状顶髻 · 整齐分发","description":"顶髻向左右展开成低扇形，中心额发整齐分开。与圆形高髻区分在顶部展开角度，适合作为整洁日常头部造型。","frames":["female.adult"],"compatibilityKey":"pony","headwear":"none","keywords":["商铺","8D1","8D1-B","扇形","顶髻","整洁"],"theme":"merchant","silhouette":"顶髻低扇状横展，中分额发","closestAssetId":"adult-high-bun","distinction":"竖高髻改为横展扇形，不用簪饰数量定义新款","readability":{"96":"扇髻展开角和分发","64":"扁扇顶髻","48":"宽平扇顶"}},
 {"id":"adult-shop-pin-knot","label":"单簪斜髻","note":"斜向发簪 · 侧后髻","description":"发髻集中在耳后外侧，一根素簪斜向穿过，发际向同侧归拢。髻体避开耳朵，不用珠饰数量表示身份。","frames":["female.adult"],"compatibilityKey":"bob","headwear":"none","keywords":["商铺","8D1","8D1-B","发簪","斜髻","侧后"],"theme":"merchant","silhouette":"一侧耳后斜髻，素簪贯穿，侧梳额发","closestAssetId":"low-bun","distinction":"低圆髻改成侧后斜长发面，靠斜向体积而非簪色区分","readability":{"96":"斜髻发面及素簪","64":"耳后偏侧发量","48":"偏侧髻体"}},
 {"id":"adult-shop-soft-cap","label":"软顶布帽","note":"低圆软顶 · 平整帽缘","description":"软布帽顶有轻微偏侧起伏，下缘平整且连续。没有硬折巾的高直帽身，整体偏低圆，男女均可搭配。","frames":["female.adult","male.adult"],"compatibilityKey":"crop","headwear":"integrated","keywords":["商铺","8D1","8D1-B","软帽","圆顶","布帽"],"theme":"merchant","silhouette":"低圆软顶，轻微偏峰，连续平帽缘","closestAssetId":"merchant-wrap","distinction":"去掉后结与包巾折面，改为整体软帽罩面","readability":{"96":"软顶偏峰和平帽缘","64":"低圆连续帽体","48":"低圆布帽"}},
 {"id":"adult-shop-square-wrap","label":"方顶包巾","note":"方折帽顶 · 宽布缘","description":"包巾在顶部折出方形平面，宽布缘沿额前围合。区别于圆顶掌柜包头，主要靠方顶与两肩式折角辨认。","frames":["male.adult"],"compatibilityKey":"crop","headwear":"integrated","keywords":["商铺","8D1","8D1-B","方顶","包巾","折面"],"theme":"merchant","silhouette":"方形平顶折片，两肩式折角，宽额缘","closestAssetId":"merchant-wrap","distinction":"低圆包头改成方顶折巾，不使用官帽翅或徽饰","readability":{"96":"方顶折片和宽缘","64":"方顶与台阶状折角","48":"低方帽顶"}},
 {"id":"adult-travel-double-coil","label":"双绕发髻","note":"双绕紧髻 · 短束带","description":"两侧上方各有一个向后绕紧的小髻，中央额发保持中分。与儿童双髻不同，成年发髻贴近头顶、收得更紧。","frames":["female.adult"],"compatibilityKey":"pony","headwear":"none","keywords":["行旅","8D1","8D1-B","双绕","紧髻","双结"],"theme":"traveler","silhouette":"两侧上方紧贴的小绕髻，中分额发","closestAssetId":"adult-high-bun","distinction":"单个高髻分为两个向后收紧的绕髻，位置远离耳廓","readability":{"96":"双绕髻和短束带","64":"对称双结轮廓","48":"低双髻"}},
 {"id":"adult-travel-kerchief","label":"垂角风巾","note":"斜覆巾面 · 两侧垂角","description":"斜覆布巾包住头顶，两侧垂角落至颈旁但不盖住面部。相较短包巾，辨识依靠两条连在帽身上的长布面。","frames":["female.adult"],"compatibilityKey":"crop","headwear":"integrated","keywords":["行旅","8D1","8D1-B","风巾","垂角","包覆"],"theme":"traveler","silhouette":"斜覆完整巾面，两侧长垂角","closestAssetId":"adult-traveler-wrap","distinction":"单侧短布尾改为两侧连帽身的长布面","readability":{"96":"斜巾面和双垂角连接","64":"颈旁两片布尾","48":"双垂角包巾"}},
 {"id":"adult-travel-straw-hat","label":"宽檐斗笠","note":"低锥笠顶 · 宽展帽檐","description":"低锥形笠顶向两侧展开成宽檐，下缘完整盖过额发。笠绳在后层，面部不被绳线横穿；男女共用，不限制职业。","frames":["female.adult","male.adult"],"compatibilityKey":"crop","headwear":"integrated","keywords":["行旅","8D1","8D1-B","斗笠","宽檐","草编"],"theme":"traveler","silhouette":"低锥笠顶，连续宽檐，后层笠绳","closestAssetId":"adult-traveler-wrap","distinction":"贴头包巾改为横向展开的整片笠檐，帽身覆盖额发","readability":{"96":"锥顶、帽檐和笠绳","64":"横展宽檐","48":"三角笠顶加宽檐"}},
 {"id":"adult-travel-high-tail","label":"高束垂尾","note":"高位束发 · 弧形垂尾","description":"高位发束向后上方扬起再垂落，呈现清楚的单侧弧形尾部。与松束、半束长发相比，变化集中在头顶外轮廓。","frames":["male.adult"],"compatibilityKey":"pony","headwear":"none","keywords":["行旅","8D1","8D1-B","高束","垂尾","后扬"],"theme":"traveler","silhouette":"单侧高束回弧尾，后扬外包络","closestAssetId":"adult-half-up","distinction":"肩边垂发改成高位后扬弧尾，不额外增大头框","readability":{"96":"高束回弧与短束带","64":"单侧上扬发量","48":"后扬顶尾"}},
] as const satisfies readonly ThemeCatalogOption[];

export const themeOutfitOptions=[
 {"id":"adult-home-soft-cross","label":"柔缘交领","note":"柔和肩线 · 浅缘斜襟","description":"浅色窄领沿内衫斜向贯通胸口，肩线舒缓。日常感来自小幅叠领和完整衣片，不在胸像下缘添加腰带。","frames":["female.adult","male.adult"],"compatibilityKey":"tee","keywords":["常服","8D1","8D1-A","柔缘","交领","素衫","普通","日常"],"theme":"common","silhouette":"舒缓肩线，浅色窄缘，浅交叠衣片","closestAssetId":"commoner","distinction":"领口交叠更浅，转折更圆顺；不以改色定义新款","readability":{"96":"浅交领转折和柔肩线","64":"轻薄斜领","48":"浅斜领和柔肩"}},
 {"id":"adult-home-round-open","label":"团口素衫","note":"团形领口 · 短直开口","description":"团形小领在正面接一条窄直开口，与闭合团领、宽缘对襟区分。系结只辅助结构，小尺寸主要看圆口和直襟。","frames":["female.adult","male.adult"],"compatibilityKey":"tee","keywords":["常服","8D1","8D1-A","团领","直襟","素色","普通","日常"],"theme":"common","silhouette":"团形小领，正中窄直开口","closestAssetId":"adult-service-robe","distinction":"偏侧闭合改成正中短直襟，圆口与中线相接","readability":{"96":"团口和短直襟连接","64":"圆口接直襟","48":"圆口竖开口"}},
 {"id":"adult-home-short-over","label":"薄褂叠衫","note":"方形开口 · 薄褂外搭","description":"薄外褂在胸前形成完整方形开口，里面露出交领衫。方口下方仍是连续衣片，不把裙腰画到胸口。","frames":["female.adult"],"compatibilityKey":"knit","keywords":["常服","8D1","8D1-A","方口","叠穿","薄褂","普通","日常"],"theme":"common","silhouette":"方形外褂开口，交领内衫，完整前片","closestAssetId":"adult-female-ruqun","distinction":"单层交领改为方口薄褂叠穿，腰部不进入胸像","readability":{"96":"方口包住交领内衫","64":"方形开口与双层衣片","48":"方口外褂"}},
 {"id":"adult-home-deep-wrap","label":"深襟常衫","note":"深交叠前片 · 竖向大襟","description":"较深的交叠衣襟斜向中下胸，前片形成较整齐的竖向面积。比短交领更深长，不依赖额外腰带表示长衫。","frames":["male.adult"],"compatibilityKey":"shirt","keywords":["常服","8D1","8D1-A","深襟","大襟","交领","普通","日常"],"theme":"common","silhouette":"深交叠大襟，较直的前片走势","closestAssetId":"adult-male-short-robe","distinction":"领边在中下胸更深交叠，不以底部横带表示长衫","readability":{"96":"深襟走向与整面前片","64":"长斜交叠","48":"深斜襟"}},
 {"id":"adult-work-shoulder-vest","label":"护肩短褂","note":"宽肩外褂 · 两片前身","description":"无袖外褂覆盖肩头，前片向下连续展开，交领内衫在中间露出。护肩来自衣片宽度，不画成围裙吊带或硬甲。","frames":["female.adult","male.adult"],"compatibilityKey":"jacket","keywords":["劳作","8D1","8D1-A","护肩","无袖","外褂"],"theme":"labor","silhouette":"宽护肩，无袖两片前身，交领内衫","closestAssetId":"adult-shop-assistant","distinction":"外搭盖到肩外，形成宽护肩；不是胸前两根带子","readability":{"96":"护肩与两片前身连接","64":"外展护肩和中间开口","48":"宽护肩外褂"}},
 {"id":"adult-work-slant-coat","label":"斜襟短褐","note":"团口斜闭合 · 收窄肩形","description":"团形内领与偏侧斜襟连接，主衣片收窄，留一处低对比补缀。区别于普通交领在斜闭合走向，不靠补丁数量识别。","frames":["male.adult"],"compatibilityKey":"jacket","keywords":["劳作","8D1","8D1-A","斜襟","短褐","补缀"],"theme":"labor","silhouette":"收窄肩身，团内领接斜闭合大襟","closestAssetId":"adult-service-robe","distinction":"主衣片更收拢，斜襟延伸到一侧，不靠补丁数量识别","readability":{"96":"团内领与侧斜襟","64":"窄肩斜闭合","48":"收肩斜襟"}},
 {"id":"adult-work-tucked-jacket","label":"窄缘短襦","note":"窄肩深领 · 收紧前片","description":"短襦肩形与胸前衣片收拢，深交领用窄缘贯通，下摆在画布外。保持简洁，没有悬空绑带或胸口腰封。","frames":["female.adult"],"compatibilityKey":"jacket","keywords":["劳作","8D1","8D1-A","窄缘","短襦","深交领"],"theme":"labor","silhouette":"窄肩深交领，收紧前片，无外搭","closestAssetId":"adult-female-work","distinction":"两层女工小褂改为单层收束短襦，取消漂浮绑带","readability":{"96":"深交领与收紧前片","64":"窄肩深斜襟","48":"紧凑单层短襦"}},
 {"id":"adult-work-collarless","label":"无领外褂","note":"低位开口 · 分离前片","description":"无领外褂从肩头连成完整两片前身，宽开口露出团领内衫。外衣向两侧铺到胸像下缘，不把前片收成吊带。","frames":["female.adult","male.adult"],"compatibilityKey":"jacket","keywords":["劳作","8D1","8D1-A","无领","外褂","内衫"],"theme":"labor","silhouette":"无领宽开口，两片外衣从肩头铺到下缘","closestAssetId":"adult-shop-assistant","distinction":"短窄对襟改为大面积露内衫的无领外褂，左右是完整衣片","readability":{"96":"整片外褂和团领内衫","64":"宽开口与两片外衣","48":"敞口外褂"}},
 {"id":"adult-shop-bordered-gown","label":"双缘襟衫","note":"双道宽缘 · 对襟前片","description":"对襟两侧各有连续宽门襟与一道浅缘，中间留出内衫间距。两处系结落在明确前片上，不挤成细中缝，也不用徽章表示官职。","frames":["female.adult","male.adult"],"compatibilityKey":"knit","keywords":["商铺","8D1","8D1-B","双缘","对襟","宽缘"],"theme":"merchant","silhouette":"双道宽门襟，留出中间间距，整洁对襟","closestAssetId":"merchant","distinction":"门襟加厚成面并加一道浅缘，系结落在两边前片而非细中缝","readability":{"96":"双缘门襟和系结落点","64":"有间距的宽对襟","48":"宽直门襟"}},
 {"id":"adult-shop-short-vest","label":"短领店褂","note":"短折领口 · 无袖前片","description":"短领外褂沿胸前转折为窄对襟，团领内衫与外褂分层。肩部比护肩短褂轻窄，可搭配任何成年居民。","frames":["female.adult","male.adult"],"compatibilityKey":"knit","keywords":["商铺","8D1","8D1-B","短领","店褂","无袖"],"theme":"merchant","silhouette":"轻窄肩部，短折领外褂，团领内衫","closestAssetId":"adult-shop-assistant","distinction":"交领内衫改成团领，短折领外搭在颈侧形成开口","readability":{"96":"短折领与团领叠层","64":"窄肩短领外褂","48":"轻窄双前片"}},
 {"id":"adult-shop-pleated-jacket","label":"折领铺衫","note":"短折领片 · 整齐叠穿","description":"左右短折领向外翻出浅色衬面，交领内衫藏在其下。依靠领片折面与平整肩形区分，不扩展独立饰品。","frames":["female.adult"],"compatibilityKey":"shirt","keywords":["商铺","8D1","8D1-B","折领","翻折","铺衫"],"theme":"merchant","silhouette":"两片短翻领，浅衬面，交领内衫收在里面","closestAssetId":"adult-female-work","distinction":"直前襟改为向外翻的短领面，不让内领伸到胸前","readability":{"96":"短翻领与内领遮挡","64":"两侧短折领片","48":"浅色双翻领"}},
 {"id":"adult-shop-side-robe","label":"侧襟长衣","note":"圆领偏闭合 · 整面前襟","description":"圆领连接偏向右侧的宽襟，胸前保留一块完整主衣片。与正中对襟区分在闭合位置，没有职业专用胸牌。","frames":["male.adult"],"compatibilityKey":"shirt","keywords":["商铺","8D1","8D1-B","侧襟","圆领","长衣"],"theme":"merchant","silhouette":"圆领偏侧宽闭合，胸前整面","closestAssetId":"adult-male-long-robe","distinction":"小幅团领扣合加宽为偏侧大襟，闭合位置更明确","readability":{"96":"圆领接偏侧襟面","64":"偏右闭合的整面胸襟","48":"偏侧襟面"}},
 {"id":"adult-travel-shoulder-cape","label":"短披肩","note":"两片披肩 · 宽展肩部","description":"两片短披肩从颈部包向肩外，内衫与中间开口清楚分离。披肩边缘止于上胸，主衣片继续向下，系绳连接两侧。","frames":["female.adult","male.adult"],"compatibilityKey":"jacket","keywords":["行旅","8D1","8D1-B","披肩","包裹","外搭"],"theme":"traveler","silhouette":"两片短披肩向肩外展开，胸前保留内衫","closestAssetId":"adult-winter-coat","distinction":"纵向夹袄前片改为横向短披肩，不塞入腰带或护甲","readability":{"96":"披肩外展与内衫连接","64":"肩外两片披风形","48":"宽展披肩"}},
 {"id":"adult-travel-cross-coat","label":"裹襟行衣","note":"宽裹交领 · 厚实肩形","description":"宽交领斜裹上胸并连续接入衣片，肩部厚实。包裹感来自宽大的领面，不另外画一条悬空围脖。","frames":["female.adult","male.adult"],"compatibilityKey":"knit","keywords":["行旅","8D1","8D1-B","裹襟","宽领","厚衣"],"theme":"traveler","silhouette":"厚实肩形，宽裹领斜包上胸","closestAssetId":"scholar","distinction":"平整书生交领改为宽厚包裹领面和更宽肩身","readability":{"96":"宽裹领的厚度与连接","64":"宽领和厚肩","48":"包裹宽斜领"}},
 {"id":"adult-travel-shawl-jacket","label":"披帛罩衫","note":"斜搭披帛 · 连续肩面","description":"宽披帛由一侧肩头斜搭到另一侧，衬边随布面连续转折。与对称披肩区分在斜向大色面，不画成细吊带。","frames":["female.adult"],"compatibilityKey":"knit","keywords":["行旅","8D1","8D1-B","披帛","斜搭","罩衫"],"theme":"traveler","silhouette":"斜向披帛连接双肩，连续衬缘，不对称前面","closestAssetId":"adult-female-ruqun","distinction":"单交领改为横斜跨肩布面，不把披帛画成细肩带","readability":{"96":"连续披帛折面与衬缘","64":"不对称跨肩布面","48":"横斜披帛"}},
 {"id":"adult-travel-high-coat","label":"厚领行袍","note":"包颈厚缘 · 合拢前襟","description":"厚缘从颈旁向下接入门襟，内衬形成短而有厚度的领面。比常服更包裹，避免尖领、金属扣等现代制服符号。","frames":["male.adult"],"compatibilityKey":"knit","keywords":["行旅","8D1","8D1-B","厚领","包颈","行袍"],"theme":"traveler","silhouette":"包颈厚缘，合拢长前襟，较宽肩形","closestAssetId":"adult-winter-coat","distinction":"宽短棉领改为从颈侧连续向下的包颈厚缘，不加尖硬立领","readability":{"96":"包颈内外厚缘","64":"合拢包颈领面","48":"厚领包裹"}},
] as const satisfies readonly ThemeCatalogOption[];

export const themeGroups=[{id:"common",label:"常服"},{id:"labor",label:"劳作"},{id:"merchant",label:"商铺"},{id:"traveler",label:"行旅"}] as const;
